@description('Azure region for all resources.')
param location string

@description('Virtual network name.')
param vnetName string

@description('Globally unique storage account name.')
param storageAccountName string

@description('Blob container used for Function deployment packages.')
param deploymentContainerName string

@description('Table used for daily history and alert state.')
param historyTableName string

@description('Resource tags.')
param tags object

var storagePrivateDnsZones = [
  {
    name: 'privatelink.blob.${environment().suffixes.storage}'
    groupId: 'blob'
  }
  {
    name: 'privatelink.queue.${environment().suffixes.storage}'
    groupId: 'queue'
  }
  {
    name: 'privatelink.table.${environment().suffixes.storage}'
    groupId: 'table'
  }
]

resource virtualNetwork 'Microsoft.Network/virtualNetworks@2024-07-01' = {
  name: vnetName
  location: location
  tags: tags
  properties: {
    addressSpace: {
      addressPrefixes: [
        '10.42.0.0/24'
      ]
    }
    subnets: [
      {
        name: 'snet-functions-integration'
        properties: {
          addressPrefix: '10.42.0.0/27'
          delegations: [
            {
              name: 'flex-consumption'
              properties: {
                serviceName: 'Microsoft.App/environments'
              }
            }
          ]
          privateEndpointNetworkPolicies: 'Disabled'
        }
      }
      {
        name: 'snet-private-endpoints'
        properties: {
          addressPrefix: '10.42.0.32/27'
          privateEndpointNetworkPolicies: 'Disabled'
        }
      }
    ]
  }
}

resource integrationSubnet 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' existing = {
  parent: virtualNetwork
  name: 'snet-functions-integration'
}

resource privateEndpointSubnet 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' existing = {
  parent: virtualNetwork
  name: 'snet-private-endpoints'
}

//checkov:skip=CKV_AZURE_43:The name is generated by main.bicep as st + uniqueString, limited to 24 lowercase alphanumeric characters.
resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: storageAccountName
  location: location
  tags: tags
  kind: 'StorageV2'
  sku: {
    name: 'Standard_ZRS'
  }
  properties: {
    accessTier: 'Hot'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
    defaultToOAuthAuthentication: true
    supportsHttpsTrafficOnly: true
    minimumTlsVersion: 'TLS1_2'
    publicNetworkAccess: 'Disabled'
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Deny'
    }
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: storageAccount
  name: 'default'
  properties: {
    deleteRetentionPolicy: {
      enabled: true
      days: 7
    }
  }
}

resource deploymentContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: blobService
  name: deploymentContainerName
  properties: {
    publicAccess: 'None'
  }
}

resource tableService 'Microsoft.Storage/storageAccounts/tableServices@2023-05-01' = {
  parent: storageAccount
  name: 'default'
}

resource historyTable 'Microsoft.Storage/storageAccounts/tableServices/tables@2023-05-01' = {
  parent: tableService
  name: historyTableName
}

resource privateDnsZones 'Microsoft.Network/privateDnsZones@2020-06-01' = [
  for zone in storagePrivateDnsZones: {
    name: zone.name
    location: 'global'
    tags: tags
  }
]

resource privateDnsZoneLinks 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = [
  for (zone, index) in storagePrivateDnsZones: {
    parent: privateDnsZones[index]
    name: 'link-${vnetName}'
    location: 'global'
    properties: {
      registrationEnabled: false
      virtualNetwork: {
        id: virtualNetwork.id
      }
    }
  }
]

resource storagePrivateEndpoints 'Microsoft.Network/privateEndpoints@2024-05-01' = [
  for zone in storagePrivateDnsZones: {
    name: 'pe-${storageAccount.name}-${zone.groupId}'
    location: location
    tags: tags
    properties: {
      subnet: {
        id: privateEndpointSubnet.id
      }
      privateLinkServiceConnections: [
        {
          name: 'connection-${zone.groupId}'
          properties: {
            privateLinkServiceId: storageAccount.id
            groupIds: [
              zone.groupId
            ]
          }
        }
      ]
    }
  }
]

resource privateDnsZoneGroups 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2024-05-01' = [
  for (zone, index) in storagePrivateDnsZones: {
    parent: storagePrivateEndpoints[index]
    name: 'default'
    properties: {
      privateDnsZoneConfigs: [
        {
          name: zone.groupId
          properties: {
            privateDnsZoneId: privateDnsZones[index].id
          }
        }
      ]
    }
  }
]

output virtualNetworkId string = virtualNetwork.id
output integrationSubnetId string = integrationSubnet.id
output storageAccountId string = storageAccount.id
output storageAccountName string = storageAccount.name
output deploymentContainerUri string = '${storageAccount.properties.primaryEndpoints.blob}${deploymentContainerName}'
