@description('Azure region for all resources.')
param location string

@description('Globally unique storage account name.')
param storageAccountName string

@description('Blob container used for Function deployment packages.')
param deploymentContainerName string

@description('Table used for daily history and alert state.')
param historyTableName string

@description('Resource tags.')
param tags object

//checkov:skip=CKV_AZURE_43:The name is generated by main.bicep as st + uniqueString, limited to 24 lowercase alphanumeric characters.
//checkov:skip=CKV_AZURE_35:Public access is required because the Flex Consumption app reaches this account over the internet with no VNet integration. Access is still restricted to Entra ID because shared keys are disabled.
resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: storageAccountName
  location: location
  tags: tags
  kind: 'StorageV2'
  sku: {
    name: 'Standard_ZRS'
  }
  properties: {
    accessTier: 'Hot'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
    defaultToOAuthAuthentication: true
    supportsHttpsTrafficOnly: true
    minimumTlsVersion: 'TLS1_2'
    publicNetworkAccess: 'Enabled'
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
    }
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: storageAccount
  name: 'default'
  properties: {
    deleteRetentionPolicy: {
      enabled: true
      days: 7
    }
  }
}

resource deploymentContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: blobService
  name: deploymentContainerName
  properties: {
    publicAccess: 'None'
  }
}

resource tableService 'Microsoft.Storage/storageAccounts/tableServices@2023-05-01' = {
  parent: storageAccount
  name: 'default'
}

resource historyTable 'Microsoft.Storage/storageAccounts/tableServices/tables@2023-05-01' = {
  parent: tableService
  name: historyTableName
}

output storageAccountName string = storageAccount.name
